version: '3.8'

services:
  backend:
    build: ./backend
    container_name: movie-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: movie-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
